language: php

sudo: false

php:
  - 7.1
  - 7.2

install:
  - composer install --no-interaction --no-suggest

script:
  - ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml
  - ./vendor/bin/php-cs-fixer fix --dry-run --diff --config php_cs.dist

branches:
  only:
    - master
    - develop
