language: php

sudo: false

php:
  - 7.1
  - 7.2

install:
  - composer install --no-interaction --no-suggest

script:
  - ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml

branches:
  only:
    - master
    - develop
